### ISSUE TITLE
No module named _libfdt

### ISSUE THREAD

**Issue by Strit** [matyas1995/uboot-rockpro64#1]
I get this error when I try to compile this.
```
Traceback (most recent call last):
  File "./tools/dtoc/dtoc", line 37, in <module>
    import dtb_platdata
  File "/build/src/u-boot-2018.09/tools/dtoc/dtb_platdata.py", line 18, in <module>
    import fdt
  File "/build/src/u-boot-2018.09/tools/dtoc/fdt.py", line 12, in <module>
    import libfdt
  File "/build/src/u-boot-2018.09/scripts/dtc/pylibfdt/libfdt.py", line 17, in <module>
    _libfdt = swig_import_helper()
  File "/build/src/u-boot-2018.09/scripts/dtc/pylibfdt/libfdt.py", line 16, in swig_import_helper
    return importlib.import_module('_libfdt')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Traceback (most recent call last):
No module named _libfdt
  File "./tools/dtoc/dtoc", line 37, in <module>
    import dtb_platdata
  File "/build/src/u-boot-2018.09/tools/dtoc/dtb_platdata.py", line 18, in <module>
    import fdt
  File "/build/src/u-boot-2018.09/tools/dtoc/fdt.py", line 12, in <module>
    import libfdt
  File "/build/src/u-boot-2018.09/scripts/dtc/pylibfdt/libfdt.py", line 17, in <module>
    _libfdt = swig_import_helper()
  File "/build/src/u-boot-2018.09/scripts/dtc/pylibfdt/libfdt.py", line 16, in swig_import_helper
    return importlib.import_module('_libfdt')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _libfdt
make[1]: *** [scripts/Makefile.spl:271: include/generated/dt-structs-gen.h] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.spl:274: spl/dts/dt-platdata.c] Error 1
make: *** [Makefile:1508: spl/u-boot-spl] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by matyas1995** [comment]
Hello,

As I see, you are getting errors about missing resources.

Have you installed the package 'dtc'? That may well be the source of your error.

I would like to warn you, the package compiles successfully but is somehow unable to boot up the rockpro. As I am currently working on enabling my rockpro with raid, lvm and lxc to be my new home server, I did not invest any effort into U-Boot as long as the original one works.

Greetings,
Matyas

**Comment by Strit** [comment]
Think we got it to build. The PKGBUILD was missing `dtc` as a dependency...

Thanks.

**Comment by matyas1995** [comment]
Thanks for the tip, I added dtc as a package dependency. 

I meant the U-Boot version that Ayufan included in his debian build for the rockpro. I created my ArchLinuxARM image by swapping out the rootfs of Debian with that of Arch Linux, described in my thread in the forum: https://forum.pine64.org/showthread.php?tid=6333

**Comment by Strit** [comment]
I started revisiting this package, since I just got my rockpro64 and it does indeed **not** boot using this package.
Do you have any progress on this, or did you abandon it?

**Comment by matyas1995** [comment]
Hello,

I have been working on creating a pacman package from Ayufans repo for arch linux, and to get to boot my server from a HDD raid with LVM. Sadly, I did not have time to investigate why the package does not boot and you could say that the project is dormant at the time. Also, I consider to just burn the bootloader into the SPI flash and not bother about it any more.
